infiltrados:
    resource: "@InfiltradosBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
